-
  get         : users
  view        : ListView
  template    : list
  Listable    : UserRepository
-
  get         : users/:id
  action      : PageController@index
  view        : ListView
  template    : list
  Listable    : UserRepository
  Paginatable : UserRepository
-
  get         : posts
  view        : ListView
  template    : list
  Listable    : PostRepository